# Generated by Django 6.0.3 on 2026-05-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plantapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
    ]
