# Generated by Django 6.0.3 on 2026-05-05 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plantapp", "0002_remove_user_gender"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="buy",
            new_name="order",
        ),
    ]
