# Generated by Django 6.0.3 on 2026-05-11 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantapp", "0005_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True, default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wishlist",
            name="product",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlisted_by",
                to="plantapp.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist_items",
                to="plantapp.user",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user", "product")},
        ),
    ]
