# Generated by Django 6.0.3 on 2026-05-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantapp", "0006_wishlist_added_at_wishlist_product_wishlist_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(null=True),
        ),
    ]
