# Generated by Django 6.0.3 on 2026-05-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantapp", "0007_alter_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_image",
            field=models.ImageField(blank=True, null=True, upload_to="user_image/"),
        ),
    ]
