# Generated by Django 6.0.3 on 2026-05-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantapp", "0008_user_user_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("landmark", models.CharField(blank=True, max_length=100, null=True)),
                ("pincode", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="landmark",
        ),
        migrations.RemoveField(
            model_name="user",
            name="pincode",
        ),
        migrations.RemoveField(
            model_name="user",
            name="state",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_image",
            field=models.ImageField(blank=True, null=True, upload_to="categorieszz/"),
        ),
    ]
